apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaTopic
  metadata:
    labels:
      strimzi.io/cluster: my-cluster
    name: orders
  spec:
    config:
      retention.ms: 604800000
      segment.bytes: 1073741824
    partitions: 10
    replicas: 3
- apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaTopic
  metadata:
    labels:
      strimzi.io/cluster: my-cluster
    name: payments
    namespace: che1sdm-serverless
  spec:
    config:
      retention.ms: 604800000
      segment.bytes: 1073741824
    partitions: 10
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
